### Task 1

In [90]:
import numpy as np

In [91]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
             [1, 7]])

In [92]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Task 2

In [93]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task3

In [94]:
N = a.shape[0]

In [95]:
tr = a_centered.transpose()

In [96]:
a_centered_sp = np.dot(tr[0], tr[1])

In [97]:
cov = a_centered_sp / (N - 1)
cov

2.0

### Task4

In [98]:
a_cov = np.cov(tr)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [99]:
if a_cov[0, 1] == cov:
    print("Right!")
else:
    print("Not right")

Right!
